import { library } from '@fortawesome/fontawesome-svg-core';
import { fab } from '@fortawesome/free-brands-svg-icons';
import {
    faGift,
    faListUl,
    faHandshake,
    faPhone,
    faPowerOff,
    faTimesCircle,
    faPaperPlane,
    faUser,
    faLock,
    faKey,
    faTrash,
    faArrowLeft,
    faTag,
    faEnvelope,
    faLightbulb,
    faBolt,
    faCog,
    faHome,
    faBars,
} from '@fortawesome/free-solid-svg-icons';

library.add(
    fab,
    faGift,
    faListUl,
    faHandshake,
    faPhone,
    faPowerOff,
    faTimesCircle,
    faPaperPlane,
    faUser,
    faLock,
    faKey,
    faTrash,
    faArrowLeft,
    faTag,
    faEnvelope,
    faLightbulb,
    faBolt,
    faCog,
    faHome,
    faBars,
);