import { library } from '@fortawesome/fontawesome-svg-core';
import {
    fab,
    faPhp,
    faPython,
    faHtml5,
    faCss3Alt
} from '@fortawesome/free-brands-svg-icons';

import {
    faGift,
    faListUl,
    faHandshake,
    faPhone,
    faPowerOff,
    faTimesCircle,
    faPaperPlane,
    faUser,
    faLock,
    faKey,
    faTrash,
    faArrowLeft,
    faTag,
    faEnvelope,
    faLightbulb,
    faBolt,
    faCog,
    faHome,
    faBars,
    faLaptop,
} from '@fortawesome/free-solid-svg-icons';

library.add(
    fab,
    faGift,
    faListUl,
    faHandshake,
    faPhone,
    faPowerOff,
    faTimesCircle,
    faPaperPlane,
    faUser,
    faLock,
    faKey,
    faTrash,
    faArrowLeft,
    faTag,
    faEnvelope,
    faLightbulb,
    faBolt,
    faCog,
    faHome,
    faBars,
    faLaptop,
    faCss3Alt,
    faHtml5,
    faPhp,
    faPython,
);