name: Deploy
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Deploy
        run: |
          yarn global add firebase-tools
          yarn install
          yarn prod
          firebase deploy --token ${FIREBASE_TOKEN} -P "my-project-1535834851092"
        
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
